### ISSUE TITLE
Write initial test suite

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/burnout-barometer#30]
You can check this to see how it's being done: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/functions/slack/slack_test.go

## Todo

In no particular order

- [x] Test barometer.go
- [x] Test config.go
- [x] Test server.go
